### ISSUE TITLE
`X-Graphql-Keys` and `X-Graphql-Query-Id` response headers missing

### ISSUE THREAD

**Issue by marco910** [wp-graphql/wp-graphql-smart-cache#269]
Hi there,

I'm using the WPGraphQL Smart Cache plugin (version 1.2.1) on two independent WordPress sites running on WP v6.4.2 and WP v6.4.3. Since a few days, I'm experiencing the same issue on both sites: In the GraphQL response, the `X-Graphql-Keys` and `X-Graphql-Query-Id` headers are both missing, which causes Varnish to not work properly (because it relies on those). Only the `X-Graphql-Url` response header is still present.
I've tested this also with accessing WP directly without any proxies but got the same response without the headers.

Here's an example query with which I'm experiencing the issue:
```
query {
  products {
    nodes {
      databaseId
      id
      title
    }
  }
}
```

Do you have an idea what could cause the issue and how to fix it?

**Comment by josephfusco** [comment]
Hey @marco910, there was a regression in the latest release of WPGraphQL. We have a fix coming shortly. Thank you for reporting this!

**Comment by jasonbahl** [comment]
For now, you can go to the GraphQL > Settings page and check the setting "Enable GraphQL Type Tracking"

It should have been defaulted to "On" but the regression was that it was off and causing the Query Analyzer to be disabled. 

We'll have a fix shortly.

**Comment by jasonbahl** [comment]
@marco910 hello, I have the following PR ready: https://github.com/wp-graphql/wp-graphql-smart-cache/pull/270

In this PR, we force-enable the GraphQL Query Analyzer which was made optional in WPGraphQL v1.20.0. 

I had the intention of leaving it enabled as a default, but I think it slipped through the cracks and the default for the setting was 'off' instead of on. 

I will leave the default as 'off' for all users of WPGraphQL, but WPGraphQL Smart Cache users will have the feature force enabled now.

**Comment by marco910** [comment]
@jasonbahl Thanks for the fix! After updating to the latest version of the WordPress plugin, it works.

**Comment by jasonbahl** [comment]
@marco910 thanks for the confirmation! Apologies for the regression and any inconvenience it caused. Glad we were able to resolve quickly for you! 🙏🏻

**Comment by marco910** [comment]
@jasonbahl We're really glad to have such a good dev team for that plugin. WPGraphQL really helps as to realize our projects with headless WP!
